services:
  postgres:
    image: postgres:17
    container_name: bdPitcherx
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: pitcherx
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - pitcherx-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pitcherx"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadminPitcherx
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - pitcherx-network
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-data:
    driver: local

networks:
  pitcherx-network:
    driver: bridge